name: Build Android App

on:
  workflow_dispatch:
    inputs:
      website_url:
        description: 'URL of the website to display in the app'
        required: true
        default: 'https://www.example.com'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Download and set up Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O sdk-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip sdk-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools
        yes | sdkmanager --sdk_root=$ANDROID_HOME "build-tools;29.0.2" "platform-tools" "platforms;android-29" "system-images;android-29;google_apis;x86"

    - name: Set up environment variables
      run: |
        echo "JAVA_HOME: $JAVA_HOME"
        echo "ANDROID_HOME: $HOME/android-sdk"
        echo "PATH: $PATH"

    - name: Create Android project structure
      run: |
        mkdir -p MyFirstApp
        cd MyFirstApp
        cat <<EOF > build.gradle
        plugins {
            id 'com.android.application'
        }

        android {
            compileSdkVersion 29
            defaultConfig {
                applicationId "com.example.myfirstapp"
                minSdkVersion 21
                targetSdkVersion 29
                versionCode 1
                versionName "1.0"
            }
            buildTypes {
                release {
                    minifyEnabled false
                    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                }
            }
        }

        dependencies {
            implementation 'androidx.appcompat:appcompat:1.2.0'
            implementation 'androidx.core:core-ktx:1.3.2'
            implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
            implementation 'com.google.android.material:material:1.3.0'
            testImplementation 'junit:junit:4.13.1'
            androidTestImplementation 'androidx.test.ext:junit:1.1.2'
            androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
        }
        EOF

        mkdir -p src/main/java/com/example/myfirstapp
        mkdir -p src/main/res/layout
        mkdir -p src/main/res/values

        cat <<EOF > src/main/AndroidManifest.xml
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android"
            package="com.example.myfirstapp">

            <application
                android:allowBackup="true"
                android:label="@string/app_name"
                android:theme="@style/Theme.AppCompat.Light.NoActionBar">
                <activity android:name=".MainActivity">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>

        </manifest>
        EOF

        cat <<EOF > src/main/res/layout/activity_main.xml
        <?xml version="1.0" encoding="utf-8"?>
        <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            <WebView
                android:id="@+id/webView"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />
        </RelativeLayout>
        EOF

        cat <<EOF > src/main/res/values/strings.xml
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <string name="app_name">MyFirstApp</string>
        </resources>
        EOF

        cat <<EOF > src/main/java/com/example/myfirstapp/MainActivity.java
        package com.example.myfirstapp;

        import android.os.Bundle;
        import android.webkit.WebView;
        import androidx.appcompat.app.AppCompatActivity;

        public class MainActivity extends AppCompatActivity {
            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                setContentView(R.layout.activity_main);
                WebView webView = findViewById(R.id.webView);
                webView.loadUrl("${{ github.event.inputs.website_url }}");
            }
        }
        EOF

    - name: Download Gradle Wrapper
      run: |
        wget https://services.gradle.org/distributions/gradle-7.6-bin.zip -O gradle.zip
        unzip gradle.zip
        export GRADLE_HOME=$PWD/gradle-7.6
        export PATH=$PATH:$GRADLE_HOME/bin

    - name: Build APK
      run: |
        cd MyFirstApp
        gradle wrapper
        ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: MyFirstApp
        path: MyFirstApp/app/build/outputs/apk/release/app-release.apk
