name: Build Android App

on:
  workflow_dispatch:
    inputs:
      website_url:
        description: 'URL of the website to display in the app'
        required: true
        default: 'https://www.example.com'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Download and set up Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O sdk-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip sdk-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools
        yes | sdkmanager --sdk_root=$ANDROID_HOME "build-tools;33.0.0" "platform-tools" "platforms;android-33"

    - name: Set up Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-8.9-bin.zip -O gradle.zip
        unzip gradle.zip -d /opt/gradle
        export PATH=$PATH:/opt/gradle/gradle-8.9/bin

    - name: Create Android project structure
      run: |
        mkdir -p MyFirstApp/src/main/java/com/example/myfirstapp
        mkdir -p MyFirstApp/src/main/res/layout
        mkdir -p MyFirstApp/src/main/res/values
        mkdir -p MyFirstApp/src/main
        mkdir -p MyFirstApp/app/src/main/java/com/example/myfirstapp
        mkdir -p MyFirstApp/app/src/main/res/layout
        mkdir -p MyFirstApp/app/src/main/res/values

        cd MyFirstApp
        echo "plugins { id 'com.android.application' version '8.1.0' }" > build.gradle
        echo "android { compileSdkVersion 33 defaultConfig { applicationId \"com.example.myfirstapp\" minSdkVersion 21 targetSdkVersion 33 versionCode 1 versionName \"1.0\" } buildTypes { release { minifyEnabled false proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' } } } dependencies { implementation 'androidx.appcompat:appcompat:1.6.1' implementation 'androidx.core:core-ktx:1.10.1' implementation 'androidx.constraintlayout:constraintlayout:2.1.4' implementation 'com.google.android.material:material:1.9.0' testImplementation 'junit:junit:4.13.2' androidTestImplementation 'androidx.test.ext:junit:1.1.5' androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1' }" > build.gradle
        echo "rootProject.name = 'MyFirstApp'\ninclude ':app'" > settings.gradle

        echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\" package=\"com.example.myfirstapp\">\n<application android:allowBackup=\"true\" android:label=\"@string/app_name\" android:theme=\"@style/Theme.AppCompat.Light.NoActionBar\">\n<activity android:name=\".MainActivity\">\n<intent-filter>\n<action android:name=\"android.intent.action.MAIN\" />\n<category android:name=\"android.intent.category.LAUNCHER\" />\n</intent-filter>\n</activity>\n</application>\n</manifest>" > app/src/main/AndroidManifest.xml
        echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<RelativeLayout xmlns:android=\"http://schemas.android.com/apk/res/android\" android:layout_width=\"match_parent\" android:layout_height=\"match_parent\">\n<WebView android:id=\"@+id/webView\" android:layout_width=\"match_parent\" android:layout_height=\"match_parent\" />\n</RelativeLayout>" > app/src/main/res/layout/activity_main.xml
        echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<resources>\n<string name=\"app_name\">MyFirstApp</string>\n</resources>" > app/src/main/res/values/strings.xml
        echo "package com.example.myfirstapp;\nimport android.os.Bundle;\nimport android.webkit.WebView;\nimport androidx.appcompat.app.AppCompatActivity;\npublic class MainActivity extends AppCompatActivity { @Override protected void onCreate(Bundle savedInstanceState) { super.onCreate(savedInstanceState); setContentView(R.layout.activity_main); WebView webView = findViewById(R.id.webView); webView.loadUrl(\"${{ github.event.inputs.website_url }}\"); } }" > app/src/main/java/com/example/myfirstapp/MainActivity.java

    - name: Build APK
      run: |
        cd MyFirstApp
        ./gradlew wrapper
        ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: MyFirstApp
        path: MyFirstApp/app/build/outputs/apk/release/app-release.apk
