name: Build Android App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt-openjdk'

    - name: Create MyFirstApp Directory
      run: |
        mkdir -p MyFirstApp/src/main/java/com/example/myfirstapp
        mkdir -p MyFirstApp/src/main/res/layout

    - name: Create build.gradle
      run: |
        cat <<EOL > MyFirstApp/build.gradle
plugins {
    id 'com.android.application' version '8.1.0'
}

android {
    compileSdkVersion 33

    defaultConfig {
        applicationId "com.example.myfirstapp"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
EOL

    - name: Create settings.gradle
      run: |
        echo "rootProject.name = 'MyFirstApp'\ninclude ':app'" > MyFirstApp/settings.gradle

    - name: Create AndroidManifest.xml
      run: |
        mkdir -p MyFirstApp/src/main/AndroidManifest.xml
        cat <<EOL > MyFirstApp/src/main/AndroidManifest.xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.myfirstapp">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.MyFirstApp">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
EOL

    - name: Create MainActivity.java
      run: |
        cat <<EOL > MyFirstApp/src/main/java/com/example/myfirstapp/MainActivity.java
package com.example.myfirstapp;

import android.app.Activity;
import android.os.Bundle;
import android.webkit.WebView;

public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        WebView webView = findViewById(R.id.webView);
        webView.loadUrl("https://www.example.com");
    }
}
EOL

    - name: Create activity_main.xml
      run: |
        cat <<EOL > MyFirstApp/src/main/res/layout/activity_main.xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <WebView
        android:id="@+id/webView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</LinearLayout>
EOL

    - name: Run Gradle Wrapper
      run: |
        cd MyFirstApp
        ./gradlew wrapper
        ./gradlew assembleRelease
